name: ltr
channels:
- kidzik
- soumith
- defaults
dependencies:
- certifi=2016.2.28
- libgfortran=3.0.0
- mpi4py=2.0.0
- mpich2=1.4.1p1
- openssl=1.0.2l
- pip=9.0.1
- python=3.6.2
- readline=6.2
- setuptools=36.4.0
- sqlite=3.13.0
- tk=8.5.18
- wheel=0.29.0
- xz=5.2.3
- zlib=1.2.11
- freeglut=3.0.0
- openblas=0.2.19
- opensim=4.0.0=15
- glib=2.50.2
- pip:
  - chardet==3.0.4
  - gym==0.9.4
  - h5py==2.7.1
  - idna==2.6
  - numpy==1.13.3
  - pandas==0.21.0
  - protobuf==3.4.0
  - psutil==5.4.1
  - pyglet==1.2.4
  - python-dateutil==2.6.1
  - pytz==2017.3
  - redis==2.10.6
  - requests==2.18.4
  - scipy==1.0.0
  - six==1.11.0
  - tensorflow==1.1.0
  - urllib3==1.22
  - werkzeug==0.12.2
